source 'https://rubygems.org'

gem 'rails', '4.2.4'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'

gem 'turbolinks'

gem 'jbuilder', '~> 2.0'

gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do

  gem 'byebug'
end

gem 'bootstrap-sass', '~> 3.3', '>= 3.3.5.1'

gem 'simple_form', '~> 3.2'

gem 'pry-rails'

gem "paperclip", "~> 4.3"

gem 'bcrypt', '~> 3.1', '>= 3.1.10'

group :development do

  gem 'web-console', '~> 2.0'

  gem 'spring'
end
